eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    fetch-registry: true
  instance:
    hostname: localhost
jwt:
  secret_key: "secret"
spring:
  application:
    name: config-server-prod
